file_format: "1"
id: charybdis
name: Charybdis
type: shield
url: https://github.com/Bastardkb/Charybdis/
requires: [pro_micro]
features:
  - Keys
  - Miryoku Colemak DH
  - Mouse keys pointer
  - Trackball pointer
  - Bluetooth/USB
siblings:
  - charybdis_left_bt
  - charybdis_right_bt
